// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

pub type MoonLatitude = f64;
pub type MoonPhase = f64;
